# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapp-ntest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ntestacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_daf1465ee5504d3e8f067773a0abd564 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_77adc66ee1214ad1be57e8cf621bdb4c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ntestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_daf1465ee5504d3e8f067773a0abd564 }}/ntest-acr-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-ntest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_75e3caa152f14b86b5069e50e229516f }}
        images: 'ntestacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_daf1465ee5504d3e8f067773a0abd564 }}/ntest-acr-image:${{ github.sha }}'